
trigger:
- develop

pool:
  vmImage: 'windows-2022'

steps:
- task: CmdLine@2
  inputs:
    script: 'dotnet workload install maui'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'FrontEnd.sln'
    arguments: '-c Release -f net6.0-android'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'